from llm_sdk import Small_LLM_Model  # type: ignore[attr-defined]
from typing import List, Dict, Optional, Any
import json
import sys
from src.object.Func_def import Func_def
from src.object.debug import Debug


class LLMWrapper():
    def __init__(self, model_name: str = 'Qwen/Qwen3-0.6B'):
        self.model = Small_LLM_Model(model_name)

    def encode_text(self, text: str) -> List[int]:
        """
        Function passed as 'encoder_func'.
        Converts text -> Tensor [[1, 2, 3]] -> List of IDs [1, 2, 3].
        Uses the SDK for the BPE algorithm (O(N^2) complexity),
        but constrained decoding validation relies exclusively
        on the vocabulary loaded in load_vocab().
        """
        tensor_ids = self.model.encode(text)  # [[1, 2, 3]]
        return list(tensor_ids.tolist()[0])  # [1, 2, 3]

    def decode_ids(self, ids: List[int]) -> str:
        """
        Converts a list of IDs -> text.
        Manual decoding using the loaded vocabulary.
        Does not depend on the SDK.
        """
        text = "".join(self.id_to_tk_str.get(tid, "") for tid in ids)
        return text.replace("Ġ", " ").replace("Ċ", "\n")

    def load_vocab(self) -> None:
        """
        Loads the vocabulary from the path provided by the SDK
        and builds id_to_tk_str and tk_str_to_id.
        Exits with sys.exit(1) on failure.
        """
        try:
            dprint = Debug().dprint
            vocab_path = self.model.get_path_to_vocab_file()
            dprint(f"\n    [DEBUG] Reading vocabulary from: {vocab_path}")
            with open(vocab_path, 'r', encoding='utf-8') as f:
                raw = json.load(f)

            dprint(f"\n    [DEBUG] Type of raw: {type(raw)}")
            dprint(
                "\n    [DEBUG] Content sample: "
                f"{list(raw.items())[:3]}"
            )

            if not isinstance(raw, dict):
                raise TypeError("Vocabulary is not a dictionary")

            # get token string  Example: id_to_tk_str[12] -> "ĠHello"
            self.id_to_tk_str = {int(v): k for k, v in raw.items()}
            # get token id      Example: tk_str_to_id["ĠHello"] -> 12
            self.tk_str_to_id = {k: int(v) for k, v in raw.items()}

        except Exception as e:
            print(f"[ERROR] loading vocabulary: {e}")
            sys.exit(1)

    def get_logits(self, input_ids: List[int]) -> List[float]:
        """
        Returns the logits (list of floats) for the input_ids sequence.
        """
        try:
            logits = self.model.get_logits_from_input_ids(input_ids)
            return list(logits)
        except Exception as e:
            print(f'[ERROR] requesting logits: {e}')
            sys.exit(1)

    def ia_response(
        self,
        full_tk: List[int],
        prompt_tk: List[int],
        func_defs: List[Func_def]
    ) -> Dict[str, Any]:
        """
        Orchestrates the full generation with constrained decoding.
        Returns a dict with prompt, fn_name and args.
        """
        generated_ids: List[int] = self._generar_ids(
            full_tk, prompt_tk, func_defs)

        text: str = self._ids_a_text(generated_ids)
        result: Dict[str, Any] = self._text_a_dict(text)

        return result

    def _ids_a_text(self, ids: List[int]) -> str:
        """
        Converts a list of generated IDs into text.
        """
        return self.decode_ids(ids).strip()

    def _text_a_dict(self, text: str) -> Dict[str, Any]:
        """
        Parses the JSON text generated by the model -> dict.
        """
        try:
            return dict(json.loads(text))
        except json.JSONDecodeError as e:
            print(f"[ERROR] Model did not generate valid JSON: {e}")
            print(f"    [DEBUG] Received text: {repr(text)}")
            sys.exit(1)

    def _generar_ids(
            self,
            full_tk: List[int],
            prompt_tk: List[int],
            func_defs: List[Func_def]) -> List[int]:
        """
        Executes constrained decoding using logit masks to force
        the model to follow a strict JSON schema.

        Uses a state machine to guide token-by-token generation:

        States:
            0: JSON start. Forces exact sequence '{"prompt": "'.
            1: Prompt content. Injects original prompt tokens
               (escaping double quotes) and closes with '", '.
            2: Function key. Forces exact sequence '"fn_name": "'.
            3: Function name. Free generation until closing quote.
               Identifies the chosen function to know its parameters.
            35/36: Transition. Ensures a clean ', ' separator
                   after the function name.
            4: Args start. Forces exact sequence '"args": {'.
            5: Dynamic args. For each parameter of the detected
               function:
               - Forces the exact key (e.g. '"param": ').
               - Controls type: string forces quotes; number
                 allows digits.
               - Manages commas and spaces between arguments.

        Finishes automatically when brace_count reaches zero,
        guaranteeing a closed JSON object and no extra text.
        """
        current_ids: List[int] = list(full_tk)
        generated_ids: List[int] = []
        generated_text: str = ""
        max_steps: int = 600
        brace_count: int = 0
        started: bool = False
        NEG_INF = float('-inf')
        dprint = Debug().dprint

        def get_id(s: str) -> Optional[int]:
            return (
                self.tk_str_to_id.get(s)
                or self.tk_str_to_id.get("Ġ" + s)
            )

        raw_prompt = "".join(
            self.id_to_tk_str.get(t, "") for t in prompt_tk
        ).replace("Ġ", " ").replace("Ċ", "\n")

        safe_prompt = raw_prompt.replace('"', '\\"')
        prompt_tk = self.encode_text(safe_prompt)

        # --- Fixed sequences ---
        header_tk = self.encode_text('{"prompt": "')
        prompt_close_tk = self.encode_text('", ')
        fn_key_tk = self.encode_text('"fn_name": "')
        args_key_tk = self.encode_text('"args": {')

        # --- State ---
        estado: int = 0
        idx: int = 0
        fn_buffer: str = ""
        func_detectada = None
        arg_keys: List[str] = []

        arg_idx: int = 0
        arg_sub_idx: int = 0
        arg_state: str = "key"
        value_quote_open: bool = False

        for step in range(max_steps):
            logits = self.get_logits(current_ids)
            mask = [NEG_INF] * len(logits)

            # ---------- MASK ----------
            if estado == 0:
                if idx < len(header_tk):
                    mask[header_tk[idx]] = 0.0
                    logits = mask

            elif estado == 1:
                total = len(prompt_tk) + len(prompt_close_tk)
                if idx < len(prompt_tk):
                    mask[prompt_tk[idx]] = 0.0
                    logits = mask
                elif idx < total:
                    close_idx = idx - len(prompt_tk)
                    mask[prompt_close_tk[close_idx]] = 0.0
                    logits = mask

            elif estado == 2:
                if idx < len(fn_key_tk):
                    mask[fn_key_tk[idx]] = 0.0
                    logits = mask

            elif estado == 3:
                pass  # free generation

            elif estado == 35:
                if idx == 0:
                    cid = get_id(',')
                    if cid is not None:
                        mask[cid] = 0.0
                        logits = mask
                elif idx == 1:
                    sid = get_id(' ') or get_id('Ġ')
                    if sid is not None:
                        mask[sid] = 0.0
                        logits = mask

            elif estado == 36:
                sid = get_id(' ') or get_id('Ġ')
                if sid is not None:
                    mask[sid] = 0.0
                    logits = mask

            elif estado == 4:
                if idx < len(args_key_tk):
                    mask[args_key_tk[idx]] = 0.0
                    logits = mask

            elif estado == 5:
                if func_detectada and arg_idx < len(arg_keys):
                    current_key = arg_keys[arg_idx]
                    current_type = (
                        func_detectada.parameters[current_key]['type']
                    )

                    if arg_state == "key":
                        seq = self.encode_text(f'"{current_key}": ')
                        if arg_sub_idx < len(seq):
                            mask[seq[arg_sub_idx]] = 0.0
                            logits = mask

                    elif arg_state == "value":
                        if current_type == 'string':
                            if not value_quote_open:
                                q = get_id('"')
                                if q is not None:
                                    mask[q] = 0.0
                                    logits = mask
                        elif current_type == 'number':
                            pass  # free generation

                    elif arg_state == "sep":
                        if arg_idx < len(arg_keys) - 1:
                            if arg_sub_idx == 0:
                                cid = get_id(',')
                                if cid is not None:
                                    mask[cid] = 0.0
                                    logits = mask
                            elif arg_sub_idx == 1:
                                sid = get_id(' ') or get_id('Ġ')
                                if sid is not None:
                                    mask[sid] = 0.0
                                    logits = mask
                        else:
                            q = get_id('}')
                            if q is not None:
                                mask[q] = 0.0
                                logits = mask
                else:
                    q = get_id('}')
                    if q is not None:
                        mask[q] = 0.0
                        logits = mask

            # ---------- CHOOSE TOKEN ----------
            top_id = max(range(len(logits)), key=lambda i: logits[i])

            # INTERCEPT: last numeric arg cannot carry a comma
            if (estado == 5 and arg_state == "value"
                    and func_detectada
                    and arg_idx == len(arg_keys) - 1):
                current_key = arg_keys[arg_idx]
                is_number = (
                    func_detectada.parameters[current_key]['type']
                    == 'number'
                )
                if is_number:
                    token_str_check = self.id_to_tk_str.get(top_id, "")
                    if ',' in token_str_check:
                        forced_id = get_id('}')
                        if forced_id is not None:
                            top_id = forced_id

            current_ids.append(top_id)
            generated_ids.append(top_id)
            token_str = self.id_to_tk_str.get(top_id, "<​UNK>")
            generated_text += token_str

            dprint(
                f"    [DEBUG] step={step:3d} estado={estado} "
                f"idx={idx} arg_state={arg_state:4s} "
                f"arg_idx={arg_idx}/{len(arg_keys)} "
                f"tok={repr(token_str):16s} brace={brace_count} "
                f"buf={repr(fn_buffer):30s}"
            )

            # ---------- BRACE COUNTER ----------
            for char in token_str:
                if char == '{':
                    brace_count += 1
                    started = True
                elif char == '}':
                    brace_count -= 1
            if started and brace_count == 0:
                dprint(f"    [DEBUG] JSON complete at step {step}")
                break

            # ---------- TRANSITIONS ----------
            if estado == 0:
                idx += 1
                if idx >= len(header_tk):
                    estado, idx = 1, 0

            elif estado == 1:
                idx += 1
                if idx >= len(prompt_tk) + len(prompt_close_tk):
                    estado, idx = 2, 0

            elif estado == 2:
                idx += 1
                if idx >= len(fn_key_tk):
                    estado, idx, fn_buffer = 3, 0, ""

            elif estado == 3:
                if '"' in token_str:
                    partes = token_str.split('"', 1)
                    fn_buffer += partes[0]
                    clean = fn_buffer.strip()
                    dprint(f"    [DEBUG] Detected name: {repr(clean)}")
                    if func_defs:
                        for fd in func_defs:
                            if fd.name == clean:
                                func_detectada = fd
                                arg_keys = list(fd.parameters.keys())
                                dprint(
                                    "    [DEBUG] Function OK: "
                                    f"{fd.name} args={arg_keys}"
                                )
                                break
                    resto = partes[1] if len(partes) > 1 else ""
                    if (resto.startswith(', ')
                            or resto.startswith(',Ġ')):
                        estado, idx = 4, 0
                    elif resto.startswith(','):
                        estado, idx = 36, 0
                    else:
                        estado, idx = 35, 0
                else:
                    fn_buffer += token_str

            elif estado == 35:
                idx += 1
                if idx >= 2:
                    estado, idx = 4, 0

            elif estado == 36:
                estado, idx = 4, 0

            elif estado == 4:
                idx += 1
                if idx >= len(args_key_tk):
                    estado = 5
                    idx = 0
                    arg_idx = 0
                    arg_sub_idx = 0
                    arg_state = "key"
                    value_quote_open = False

            elif estado == 5:
                if func_detectada and arg_idx < len(arg_keys):
                    current_key = arg_keys[arg_idx]
                    current_type = (
                        func_detectada.parameters[current_key]['type']
                    )

                    if arg_state == "key":
                        seq = self.encode_text(f'"{current_key}": ')
                        arg_sub_idx += 1
                        if arg_sub_idx >= len(seq):
                            arg_state = "value"
                            arg_sub_idx = 0
                            value_quote_open = False

                    elif arg_state == "value":
                        if current_type == 'string':
                            if not value_quote_open:
                                value_quote_open = True
                            else:
                                if '"' in token_str:
                                    after = token_str.rsplit('"', 1)[-1]
                                    if ',' in after:
                                        arg_idx += 1
                                        arg_state = "key"
                                        arg_sub_idx = 0
                                    else:
                                        arg_state = "sep"
                                        arg_sub_idx = 0
                        elif current_type == 'number':
                            if ',' in token_str:
                                if arg_idx < len(arg_keys) - 1:
                                    arg_idx += 1
                                    arg_state = "key"
                                    arg_sub_idx = 0
                                else:
                                    arg_idx = len(arg_keys)
                            elif '}' in token_str:
                                arg_idx = len(arg_keys)

                    elif arg_state == "sep":
                        if arg_idx < len(arg_keys) - 1:
                            arg_sub_idx += 1
                            if arg_sub_idx >= 2:
                                arg_idx += 1
                                arg_state = "key"
                                arg_sub_idx = 0
                        else:
                            arg_idx = len(arg_keys)

        return generated_ids
